apiVersion: apps/v1
kind: Deployment
metadata:
  name: problem-4
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: problem-4
        image: nginx
        ports:
        - containerPort: 80  
        resources:
          limits:
            memory: 16234832Ki
            cpu: 4000m
          requests:
            memory: 16234832Ki
            cpu: 4000m
---
apiVersion: v1
kind: Service
metadata:
  name: problem-4-service
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
