apiVersion: v1
kind: Namespace
metadata:
   name: problem5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: problem-5
  namespace: problem5
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: problem-5
        image: nginx
        ports:
        - containerPort: 80  
---
apiVersion: v1
kind: Service
metadata:
  name: problem-5-service
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
